// apps/runtime-bench-react/src/pages/detail/index.ts
import type { BenchPageController, ReactBenchPageRuntime } from '../shared'
import { createReactMiniProgramRoot } from '@weapp-vite/react'
import { createElement, createRef } from 'react'
import { now, patchSetData } from '../../utils/bench'
import { readFirstCommitMs } from '../shared'
import { ReactDetailPage } from './view'

const runtimes = new WeakMap<object, ReactBenchPageRuntime<BenchPageController>>()

Page({
  data: { root: { cn: [] } },
  eh(event: WechatMiniprogram.BaseEvent) {
    runtimes.get(this)?.root.dispatchEvent(event)
  },
  onLoad() {
    const loadStartedAt = now()
    const setDataCounter = { total: 0, firstCommitAt: null }
    patchSetData(this, setDataCounter)
    const controller = createRef<BenchPageController>()
    const root = createReactMiniProgramRoot(this)
    runtimes.set(this, { controller, loadStartedAt, root, setDataCounter })
    root.render(createElement(ReactDetailPage, { ref: controller, setDataCounter }))
  },
  onReady() {
    const runtime = runtimes.get(this)
    const loadStartedAt = runtime?.loadStartedAt ?? now()
    runtime?.controller.current?.finishReady(
      now() - loadStartedAt,
      runtime ? readFirstCommitMs(runtime.setDataCounter, loadStartedAt) : 0,
    )
    runtime?.root.flush()
  },
  onUnload() {
    runtimes.get(this)?.root.unmount()
    runtimes.delete(this)
  },
  readBenchState() {
    return runtimes.get(this)?.controller.current?.readBenchState()
  },
})

// apps/runtime-bench-solid/src/pages/detail/index.ts
import type { SolidBenchRuntime } from '../shared'
import { createMemo, createRoot, createSignal } from 'solid-js/dist/solid.js'
import { createSolidMiniProgramRoot } from '../../runtime'
import {
  createBenchCards,
  createEmptyMetrics,
  DETAIL_CARD_COUNT,
  now,
  patchSetData,
  summarizeBenchCards,
} from '../../utils/bench'
import { snapshot } from '../shared'

const runtimes = new WeakMap<object, SolidBenchRuntime>()

Page({
  data: {},
  onLoad() {
    const loadStartedAt = now()
    const setDataCounter = { total: 0, firstCommitAt: null }
    patchSetData(this, setDataCounter)
    const root = createSolidMiniProgramRoot(this)
    const runtime = createRoot((dispose) => {
      const [cards, setCards] = createSignal(createBenchCards(7, DETAIL_CARD_COUNT))
      const summary = createMemo(() => summarizeBenchCards(cards()))
      root.mount({ cards, summary })
      return {
        cards,
        dispose,
        metrics: createEmptyMetrics(),
        root,
        setCards,
        setDataCounter,
      }
    })
    runtime.metrics.loadToReadyMs = -loadStartedAt
    runtimes.set(this, runtime)
  },
  onReady() {
    const runtime = runtimes.get(this)
    if (!runtime) {
      return
    }
    const loadStartedAt = -runtime.metrics.loadToReadyMs
    runtime.metrics.loadToReadyMs = now() - loadStartedAt
    runtime.metrics.firstCommitMs = runtime.setDataCounter.firstCommitAt === null
      ? 0
      : runtime.setDataCounter.firstCommitAt - loadStartedAt
  },
  onUnload() {
    const runtime = runtimes.get(this)
    runtime?.root.dispose()
    runtime?.dispose()
    runtimes.delete(this)
  },
  readBenchState() {
    const runtime = runtimes.get(this)
    return runtime ? snapshot(runtime, 'solid-detail-ready') : undefined
  },
})
